# MNIST Gradio Interface - resolves Issue #1

# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zKa2T9apdS8s_VW6GXF9nCs9VArxk_YT
"""

from google.colab import drive
drive.mount('/content/drive')

import torch
import torch.nn as nn
from torchvision import transforms
from PIL import Image, ImageOps
import gradio as gr
import numpy as np

SAVE_PATH = "/content/drive/MyDrive/++DL/06_openSource/mnist_model.pth"

class SimpleCNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(1, 32, 3, padding=1), nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(32, 64, 3, padding=1), nn.ReLU(),
            nn.MaxPool2d(2)
        )
        self.fc = nn.Sequential(
            nn.Flatten(),
            nn.Linear(64 * 7 * 7, 128), nn.ReLU(),
            nn.Linear(128, 10)
        )
    def forward(self, x):
        return self.fc(self.conv(x))

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model  = SimpleCNN().to(DEVICE)
model.load_state_dict(torch.load(SAVE_PATH, map_location=DEVICE))
model.eval()
print("模型從 Drive 載入成功")

def predict(image):
    if image is None:
        return {"無輸入": 1.0}

    # 新版 Gradio 的 Sketchpad 回傳 dict，要取 "composite" key
    if isinstance(image, dict):
        image = image.get("composite", image.get("layers", [None])[0])
    if image is None:
        return {"無輸入": 1.0}

    img = Image.fromarray(image.astype("uint8"))
    img = img.convert("L")
    img = ImageOps.invert(img)
    img = img.resize((28, 28))

    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.1307,), (0.3081,))
    ])
    tensor = transform(img).unsqueeze(0).to(DEVICE)

    with torch.no_grad():
        probs = torch.softmax(model(tensor), dim=1)[0]

    return {str(i): float(probs[i]) for i in range(10)}

'''
def predict(image):
    if image is None:
        return {"錯誤": 1.0}
    img = Image.fromarray(image.astype("uint8"))
    img = img.convert("L")
    img = ImageOps.invert(img)
    img = img.resize((28, 28))
    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.1307,), (0.3081,))
    ])
    tensor = transform(img).unsqueeze(0).to(DEVICE)
    with torch.no_grad():
        probs = torch.softmax(model(tensor), dim=1)[0]
    return {str(i): float(probs[i]) for i in range(10)}
'''

demo = gr.Interface(
    fn=predict,
    inputs=gr.Sketchpad(label="在這裡畫數字 (0–9)", image_mode="RGB"),
    outputs=gr.Label(num_top_classes=3, label="預測結果（Top 3）"),
    title="MNIST 手寫數字辨識",
    description="用滑鼠在畫布上寫一個數字（0到9），模型會即時告訴你它認為是幾！"
)

demo.launch(share=True)
