# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7uBSAmZo9PKCw-XsudsUEdJT-vrgdjn

# MNIST Handwritten Digit Classifier using PyTorch
"""

!pip install torch torchvision gradio Pillow --quiet

# 掛載 Google Drive
from google.colab import drive
drive.mount('/content/drive')

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import json, os

BATCH_SIZE = 64
EPOCHS     = 5        # 改成 5，穩定超過 99%
LR         = 0.001
DEVICE     = torch.device("cuda" if torch.cuda.is_available() else "cpu")
SAVE_PATH  = "/content/drive/MyDrive/++DL/06_openSource/mnist_model.pth"   # 存到 Drive
print(f"使用設備：{DEVICE}")

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])

train_dataset = datasets.MNIST(root="./data", train=True,  download=True, transform=transform)
test_dataset  = datasets.MNIST(root="./data", train=False, download=True, transform=transform)
train_loader  = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
test_loader   = DataLoader(test_dataset,  batch_size=BATCH_SIZE, shuffle=False)

class SimpleCNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(1, 32, 3, padding=1), nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(32, 64, 3, padding=1), nn.ReLU(),
            nn.MaxPool2d(2)
        )
        self.fc = nn.Sequential(
            nn.Flatten(),
            nn.Linear(64 * 7 * 7, 128), nn.ReLU(),
            nn.Linear(128, 10)
        )
    def forward(self, x):
        return self.fc(self.conv(x))

model     = SimpleCNN().to(DEVICE)
optimizer = optim.Adam(model.parameters(), lr=LR)
criterion = nn.CrossEntropyLoss()
history   = []

for epoch in range(1, EPOCHS + 1):
    model.train()
    total_loss = 0
    for images, labels in train_loader:
        images, labels = images.to(DEVICE), labels.to(DEVICE)
        optimizer.zero_grad()
        loss = criterion(model(images), labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    avg_loss = total_loss / len(train_loader)

    model.eval()
    correct = 0
    with torch.no_grad():
        for images, labels in test_loader:
            images, labels = images.to(DEVICE), labels.to(DEVICE)
            correct += (model(images).argmax(1) == labels).sum().item()
    acc = correct / len(test_dataset) * 100
    print(f"Epoch {epoch}/{EPOCHS}  Loss: {avg_loss:.4f}  Test Acc: {acc:.2f}%")
    history.append({"epoch": epoch, "loss": round(avg_loss, 4), "accuracy": round(acc, 2)})

# 同時存到 Drive 和本地
torch.save(model.state_dict(), SAVE_PATH)
torch.save(model.state_dict(), "mnist_model.pth")
with open("results.json", "w") as f:
    json.dump(history, f, indent=2)

print(f"\n模型已存到 Drive：{SAVE_PATH}")